based/based/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from core import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.IndexView.as_view()),
    path("create_student/", views.Createstudent.as_view()),
    path("course/edit/<int:course_id>/", views.EditCourseView.as_view(), name="course_edit"),
    path("create_course/", views.CreateCourse.as_view()),
    path("all_students/", views.AllStudentsView.as_view(), name="students"),
    path("student/edit/<int:student_id>/", views.EditStudentView.as_view(), name="student_edit"),
    path("group_name=<str:group_name>/", views.NavView.as_view(), name="levels"),
    path("login/", LoginView.as_view(template_name='login.html'), name='login'),
    path("logout/", LogoutView.as_view(), name='logout'),
    path("search/", views.SearchView.as_view(), name='search'),


    path('__debug__/', include('debug_toolbar.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

based/core/models.py
from django.db import models


# Create your models here.



class Student(models.Model):
    name = models.CharField(max_length=255)
    age = models.PositiveIntegerField(default=0)
    email = models.CharField(max_length=255)
    group = models.ManyToManyField("core.Group")

    def __str__(self):
        return self.name


class Course(models.Model):
    name = models.CharField(max_length=255)
    group = models.ManyToManyField("core.Group")
    teacher = models.ForeignKey("core.Teacher", on_delete=models.SET_NULL, null=True)
    description = models.CharField(max_length=255)

    def __str__(self):
        return self.name


#on_delete=models.SET_NULL, null=True
class Teacher(models.Model):
    name = models.CharField(max_length=255)
    age = models.PositiveIntegerField(default=0)
    email = models.CharField(max_length=255)
    group = models.ManyToManyField("core.Group")
    def __str__(self):
        return self.name


class Group(models.Model):
    name = models.CharField(max_length=255)
    def __str__(self):
        return self.name

based/core/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core import validators
from django.core.validators import MaxLengthValidator
from core.models import Student, Course


class CreateCourseForm(forms.ModelForm):

    class Meta:
        model = Course
        fields = "__all__"


    def clean_name(self):
        name = self.cleaned_data["name"]
        if Course.objects.filter(name__iexact=name):
            raise forms.ValidationError("Name of the course is not unique")
        return name




class CreateStudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = "__all__"
    def save(self, *args, **kwargs):
        student = super(CreateStudentForm, self).save(*args, **kwargs)
        student.save()
        return student
    def clean_name(self):
        name = self.cleaned_data["name"]
        if Student.objects.filter(name__iexact=name):
            raise forms.ValidationError("Student name is not unique")

        return name

# class LoginForm(forms.Form):
#     username = forms.CharField()
#     password = forms.CharField(widget=forms.PasswordInput())
#
#     def clean(self):
#         self.user = User.objects.filter(username=self.cleaned_data['username']).first()
#         if self.user and self.user.check_password(self.cleaned_data['password']):
#             return self.cleaned_data
#         else:
#             raise forms.ValidationError('Username or password is wrong!')

based/core/views.py
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.db.models import Q, F
from django.shortcuts import redirect
from django.views.generic import TemplateView, ListView, FormView, CreateView, UpdateView

from django.views.generic import TemplateView
from django.db.models import Prefetch
from core.models import Teacher, Student, Group
from core.models import Course
from core.forms import CreateStudentForm, CreateCourseForm




class IndexView(ListView):
    model = Course
    template_name = 'index.html'
    paginate_by = 5

    #
    def get_queryset(self):

        queryset = super(IndexView, self).get_queryset().filter(teacher__isnull=False)
        return queryset.select_related(
            "teacher"
        ).prefetch_related(
            "group",
        )

    def get_context_data(self, *args, **kwargs):
        context = super(IndexView, self).get_context_data(*args, **kwargs)

        context['groups'] = Group.objects.all()
        context['teacher'] = Teacher.objects.all()
        return context


class NavView(ListView):
    model = Course
    template_name = 'index.html'
    paginate_by = 5

    def get_queryset(self):
        queryset = super(NavView, self).get_queryset().filter(group__name=self.kwargs["group_name"])
        return queryset.select_related(
            "teacher"
        ).prefetch_related(
            "group"
        )
class AllStudentsView(ListView):
    model = Student
    template_name = "all_students.html"

    def get_context_data(self, *args, **kwargs):
        context = super(ListView, self).get_context_data(*args, **kwargs)
        context["group"] = Group.objects.all()
        return context


class CreateCourse(CreateView):
    template_name = "create_course.html"
    model = Course
    form_class = CreateCourseForm
    success_url = "/"


class Createstudent(CreateView):
    template_name = "create_student.html"
    success_url = "/"
    form_class = CreateStudentForm

    def form_valid(self, form):
        form.save()
        return super(Createstudent, self).form_valid(form)


class EditCourseView(FormView):
    template_name = "create_course.html"
    form_class = CreateCourseForm
    success_url = '/'

    def get_form_kwargs(self):
        form_kwargs = super(EditCourseView, self).get_form_kwargs()
        form_kwargs["instance"] = get_object_or_404(Course, id=self.kwargs["course_id"])
        return form_kwargs

    def form_valid(self, form):
        form.save()
        return super(EditCourseView, self).form_valid(form)


class EditStudentView(FormView):
    template_name = "create_student.html"
    form_class = CreateStudentForm
    success_url = "/"

    def get_form_kwargs(self):
        form_kwargs = super(EditStudentView, self).get_form_kwargs()
        form_kwargs["instance"] = get_object_or_404(Student, id=self.kwargs["student_id"])
        return form_kwargs

    def form_valid(self, form):
        form.save()
        return super(EditStudentView, self).form_valid(form)


class SearchView(ListView):
    template_name = "search.html"
    model = Course
    paginate_by = 5


    def get_queryset(self):
        query = self.request.GET.get('q', None)
        if query:
            return self.model.objects.filter(
                Q(name__icontains=query) |
                Q(group__name__icontains=query) |
                Q(teacher__name__icontains=query)
            )
        return super(SearchView, self).get_queryset()

    def get_context_data(self, *args, **kwargs):
        data = super().get_context_data(**kwargs)
        data["searched"] = self.request.GET["q"]
        return data

based/core/templates/all_students.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
    <div class="row">
        <div class="col-md-3">
           <table class="table table-dark">
              <thead>
                <tr>
                  <th scope="col">id</th>
                  <th scope="col">Name</th>
                  <th scope="col">Age</th>
                  <th scope="col">Email</th>
                  <th scope="col"> </th>
                </tr>
              </thead>
              <tbody>
              {% for student in student_list%}
                <tr>
                  <th scope="row">{{ student.id }}</th>
                  <td>{{ student.name }}</td>
                  <td>{{ student.age }}</td>
                  <td>{{ student.email }}</td>
                  <td>
                      <a href="{% url "student_edit" student_id=student.id%}" class="btn btn-success">Edit</a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
        </div>
    </div>
{% endblock content %}

based/core/templates/base.html
<html>
    <head>
        <title>Texstings?!</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <a class="navbar-brand" href="/">Textings</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                  Level
                </a>
                <div class="dropdown-menu">
                    {% for group in groups %}
                        <a class="dropdown-item" href="{% url "levels" group_name=group.name %}">{{ group.name }}</a>
                    {% endfor %}
                </div>
              </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url "students" %}">All students <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    {% if user.is_authenticated %}
                        <a class="btn btn-danger" href="{% url 'logout' %}">Logout</a>
                    {% else %}
                       <a class="btn btn-primary" href="{% url 'login' %}">Login</a>
                    {% endif %}
                </li>
            </ul>
          </div>
            <form action="{% url 'search' %}" method="get" class="form-inline my-2 my-lg-0">
              <input class="form-control mr-sm-2" type="search" placeholder="Search" name="q" aria-label="Search">
              <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Search</button>
            </form>

        </nav>
        <div class="container">
            <br>
            {% block content %}
            {% endblock content %}
        </div>


        <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
    </body>
</html>

based/core/templates/create_course.html
{% extends "base.html" %}
{% block content %}
<form action="." method="post">{% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td>
                <button type="submit" class="btn btn-success">Create</button>
            </td>
        </tr>
    </table>
</form>
{% endblock content %}

based/core/templates/create_student.html
{% extends "base.html" %}
{% block content %}
 <form action="." method="post">{% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td>
                <button type="submit" class="btn btn-success">Create</button>
            </td>
        </tr>
    </table>
</form>
{% endblock content%}

based/core/templates/includes/course_loop.html
{% load core_tags %}
{% for course in course_list %}
    {% if course.id|divisibleby:2 %}
<!--    <h1> {{course.id}} </h1>-->
      <div class="col-md-3">
          <div class="card" style="margin-bottom: 10px;">
            <div class="card-body">
              <h5 class="card-title">{{ course.name }}</h5>
              <p class="card-text">{{ course.description }}</p>
              <p>
                  {% for teacher in course_list %}
                      <a href="tech">{{ course.teacher.name }}</a>
                  {% endfor %}
              </p>
              <p>
                  {% for group in course.group.all %}
                      <a href="#">{{ group.name }}</a>
                      {% if not forloop.last %}, {% endif %}
                  {% endfor %}
              </p>
              <a href="#" class="btn btn-primary">Subscribe</a>
              <a href="{% url "course_edit" course.id %}" class="btn btn-success">Edit</a>
            </div>
          </div>
      </div>
    {% endif %}
{% endfor %}

based/core/templates/index.html
{% extends "base.html" %}
{% load core_tags %}
{% block content %}

    <div class="row">
        {% for course in course_list %}
        <div class="col-md-3">
            <div class="card" style="margin-bottom: 10px;">
              <div class="card-body">
                <h5 class="card-title">{{ course.name }}</h5>
                <p class="card-text">{{ course.description }}</p>
                <p>
    <!--                {% for teacher in course_list %}-->
                        <a href="tech">{{ course.teacher.name }}</a>
    <!--                {% endfor %}-->
                </p>
                <p>
                    {% for group in course.group.all %}
                        <a href="#">{{ group.name }}</a>
                        {% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </p>
                <a href="#" class="btn btn-primary">Subscribe</a>
                <a href="{% url "course_edit" course.id %}" class="btn btn-success">Edit</a>
              </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="row">
        <h2 class="text-center"> Five products </h2>
    </div>
    <div class="row">
        {% get_five %}
    </div>
    <div>
        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>
    </div>
{% endblock content %}

based/core/templates/login.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
<form method="post">{% csrf_token %}
    <table>
        {% bootstrap_form form %}
        <tr>
            <td>
                <button type="submit" class="btn btn-success">Login</button>
            </td>
        </tr>
    </table>
</form>
{% endblock content%}

based/core/templates/search.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <h2>Your searched for {{ searched }}, length of searched word is {{ searched|length }}</h2>
        </div>
    </div>
    <div class="row">
        {% include "includes/course_loop.html" %}
        <h1></h1>
    </div>
{% endblock content %}